### ISSUE TITLE
Add user registration/login

### ISSUE THREAD

**Issue by carlosero** [sublimeconcept/tupuja-frontend#11]
## Completed
- [x] Implement Parse API function on User Service comp.
- [x] Add user login component.
- [x] Create user registration component.
- [x] Add validations (unique email, basic security password).
- [x] Change navbar according.
- [x] Logout implemented.

**Comment by cantwait** [comment]
We are almost done here, there is only one remaining issue with logIn User api function.

**Comment by carlosero** [comment]
Yeah, tomorrow I'll verify it.

**Comment by cantwait** [comment]
The error with the login method has been fixed, also I have activated user email verification now we should get an email with a link to verify the user.

**Comment by cantwait** [comment]
Logout implemented.

**Comment by cantwait** [comment]
@carlosero creo que lo podemos cerrar no ?
