### ISSUE TITLE
Bid on click, with user's credits

### ISSUE THREAD

**Issue by carlosero** [sublimeconcept/tupuja-frontend#16]
## Feature
- [x] Provide a "Bid" button.
- [x] When bidding, create a bid object related to the user and the auction
- [x] When bidding, deduct one credit from user's credits
- [x] When bidding, show an error if user's credits are lower than 0
- [x] Increment `auction.endDate` on bidding.

**Comment by sublimeconcept** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Func - Hacer BID en un auction](https://trello.com/c/IZ6WVOiu/25-func-hacer-bid-en-un-auction)
